[build]
cmd = "python backend/manage.py collectstatic --noinput"

[start]
cmd = "python backend/manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r backend/requirements.txt"]
